export LIBRELINK_EMAIL=""
export LIBRELINK_PASSWORD=""
export LIBRELINK_PATIENT=""
export LIBRELINK_REGION="https://api-eu.libreview.io"
export GLUCOSA_USE_CACHE=0
export GLUCOSA_NOTIFY_ENABLED=1
export GLUCOSA_NOTIFY_INTERVAL_MINUTES=15